# Generated by Django 4.2.2 on 2023-06-22 09:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotion', '0002_emotion_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thanks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('descriontion', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='ThanksEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('level', models.IntegerField(default=1)),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotion.emotion')),
                ('thanks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thanks.thanks')),
            ],
        ),
    ]
