# Generated by Django 4.2.2 on 2023-06-22 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0002_thanks_user_thanksemotion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thanksemotion',
            name='user',
        ),
    ]
