# Generated by Django 3.2.19 on 2023-06-22 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thanks', '0003_remove_thanksemotion_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thanks',
            old_name='descriontion',
            new_name='description',
        ),
    ]
