# Generated by Django 4.2.2 on 2023-06-27 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emotion', '0002_emotion_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('name', models.CharField(max_length=30)),
                ('positive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnappropriateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('situation', models.CharField(max_length=500)),
                ('feelings_actions', models.CharField(max_length=500)),
                ('desired_feelings_actions', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='EventsEmotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('is_real', models.BooleanField(default=True)),
                ('UnappropriateEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.unappropriateevent')),
                ('emotion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emotion.emotion')),
            ],
        ),
        migrations.CreateModel(
            name='EventsAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('is_real', models.BooleanField(default=True)),
                ('UnappropriateEvent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.unappropriateevent')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.action')),
            ],
        ),
    ]
