# Generated by Django 4.2.2 on 2023-06-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsaction',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='eventsemotion',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
