# Generated by Django 4.2.2 on 2023-07-13 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_eventsaction_level_eventsemotion_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('situation', models.CharField(max_length=500)),
                ('beliefs', models.CharField(max_length=500)),
                ('excuses', models.CharField(max_length=500)),
                ('excuses_сhecking', models.CharField(max_length=500)),
                ('necessary_actions', models.CharField(max_length=500)),
                ('actual', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
    ]
